-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 13:34:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetb2csharp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetb2csharp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetb2csharp` DEFAULT CHARACTER SET utf8 ;
USE `projetb2csharp` ;

-- -----------------------------------------------------
-- Table `projetb2csharp`.`Espece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Espece` (
  `idEspece` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEspece`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`ZonePrelevement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`ZonePrelevement` (
  `idZonePrelevement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `lat1` FLOAT NOT NULL,
  `lat2` FLOAT NOT NULL,
  `lat3` FLOAT NOT NULL,
  `lat4` FLOAT NOT NULL,
  `long1` FLOAT NOT NULL,
  `long2` FLOAT NOT NULL,
  `long3` FLOAT NOT NULL,
  `long4` FLOAT NOT NULL,
  `idPlage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZonePrelevement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `isAdmin` BIT NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Departement` (
  `idDepartement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Commune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Commune` (
  `idCommune` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `Departement_idDepartement` INT NOT NULL,
  PRIMARY KEY (`idCommune`, `Departement_idDepartement`),
  INDEX `fk_Commune_Departement1_idx` (`Departement_idDepartement` ASC),
  CONSTRAINT `fk_Commune_Departement1`
    FOREIGN KEY (`Departement_idDepartement`)
    REFERENCES `projetb2csharp`.`Departement` (`idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Plage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Plage` (
  `idPlage` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idCommune` INT NOT NULL,
  `idDepartement` INT NOT NULL,
  `ndEspecesDifferentes` INT NOT NULL,
  `surface` FLOAT NOT NULL,
  PRIMARY KEY (`idPlage`, `idCommune`, `idDepartement`),
  INDEX `fk_Plage_Commune1_idx` (`idCommune` ASC, `idDepartement` ASC),
  CONSTRAINT `fk_Plage_Commune1`
    FOREIGN KEY (`idCommune` , `idDepartement`)
    REFERENCES `projetb2csharp`.`Commune` (`idCommune` , `Departement_idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Etude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Etude` (
  `idEtude` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `nbPersonneCompteuse` INT NOT NULL,
  `nbTotalEspeceRencontree` INT NOT NULL,
  PRIMARY KEY (`idEtude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Etude_has_Plage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Etude_has_Plage` (
  `Etude_idEtude` INT NOT NULL,
  `Plage_idPlage` INT NOT NULL,
  PRIMARY KEY (`Etude_idEtude`, `Plage_idPlage`),
  INDEX `fk_Etude_has_Plage_Plage1_idx` (`Plage_idPlage` ASC),
  INDEX `fk_Etude_has_Plage_Etude1_idx` (`Etude_idEtude` ASC),
  CONSTRAINT `fk_Etude_has_Plage_Etude1`
    FOREIGN KEY (`Etude_idEtude`)
    REFERENCES `projetb2csharp`.`Etude` (`idEtude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etude_has_Plage_Plage1`
    FOREIGN KEY (`Plage_idPlage`)
    REFERENCES `projetb2csharp`.`Plage` (`idPlage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`ZonePrelevement_has_Plage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`ZonePrelevement_has_Plage` (
  `ZonePrelevement_idZonePrelevement` INT NOT NULL,
  `Plage_idPlage` INT NOT NULL,
  `Plage_idCommune` INT NOT NULL,
  `Plage_idDepartement` INT NOT NULL,
  PRIMARY KEY (`ZonePrelevement_idZonePrelevement`, `Plage_idPlage`, `Plage_idCommune`, `Plage_idDepartement`),
  INDEX `fk_ZonePrelevement_has_Plage_Plage1_idx` (`Plage_idPlage` ASC, `Plage_idCommune` ASC, `Plage_idDepartement` ASC),
  INDEX `fk_ZonePrelevement_has_Plage_ZonePrelevement1_idx` (`ZonePrelevement_idZonePrelevement` ASC),
  CONSTRAINT `fk_ZonePrelevement_has_Plage_ZonePrelevement1`
    FOREIGN KEY (`ZonePrelevement_idZonePrelevement`)
    REFERENCES `projetb2csharp`.`ZonePrelevement` (`idZonePrelevement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZonePrelevement_has_Plage_Plage1`
    FOREIGN KEY (`Plage_idPlage` , `Plage_idCommune` , `Plage_idDepartement`)
    REFERENCES `projetb2csharp`.`Plage` (`idPlage` , `idCommune` , `idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Espece_has_Plage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Espece_has_Plage` (
  `Espece_idEspece` INT NOT NULL,
  `Plage_idPlage` INT NOT NULL,
  `densite` FLOAT NOT NULL,
  `populationTotale` FLOAT NOT NULL,
  PRIMARY KEY (`Espece_idEspece`, `Plage_idPlage`),
  INDEX `fk_Espece_has_Plage_Plage1_idx` (`Plage_idPlage` ASC),
  INDEX `fk_Espece_has_Plage_Espece1_idx` (`Espece_idEspece` ASC),
  CONSTRAINT `fk_Espece_has_Plage_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`Espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Espece_has_Plage_Plage1`
    FOREIGN KEY (`Plage_idPlage`)
    REFERENCES `projetb2csharp`.`Plage` (`idPlage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Espece_has_ZonePrelevement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Espece_has_ZonePrelevement` (
  `Espece_idEspece` INT NOT NULL,
  `ZonePrelevement_idZonePrelevement` INT NOT NULL,
  `nombreEspeceZone` INT NOT NULL,
  PRIMARY KEY (`Espece_idEspece`, `ZonePrelevement_idZonePrelevement`),
  INDEX `fk_Espece_has_ZonePrelevement_ZonePrelevement1_idx` (`ZonePrelevement_idZonePrelevement` ASC),
  INDEX `fk_Espece_has_ZonePrelevement_Espece1_idx` (`Espece_idEspece` ASC),
  CONSTRAINT `fk_Espece_has_ZonePrelevement_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`Espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Espece_has_ZonePrelevement_ZonePrelevement1`
    FOREIGN KEY (`ZonePrelevement_idZonePrelevement`)
    REFERENCES `projetb2csharp`.`ZonePrelevement` (`idZonePrelevement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`Etude_has_Espece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetb2csharp`.`Etude_has_Espece` (
  `Etude_idEtude` INT NOT NULL,
  `Espece_idEspece` INT NOT NULL,
  `densiteTotaleEspece` FLOAT NOT NULL,
  PRIMARY KEY (`Etude_idEtude`, `Espece_idEspece`),
  INDEX `fk_Etude_has_Espece_Espece1_idx` (`Espece_idEspece` ASC),
  INDEX `fk_Etude_has_Espece_Etude1_idx` (`Etude_idEtude` ASC),
  CONSTRAINT `fk_Etude_has_Espece_Etude1`
    FOREIGN KEY (`Etude_idEtude`)
    REFERENCES `projetb2csharp`.`Etude` (`idEtude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etude_has_Espece_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`Espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
