-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 14:17:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetb2csharp
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetb2csharp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetb2csharp` ;

-- -----------------------------------------------------
-- Schema projetb2csharp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetb2csharp` DEFAULT CHARACTER SET utf8 ;
USE `projetb2csharp` ;

-- -----------------------------------------------------
-- Table `projetb2csharp`.`departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`departement` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`departement` (
  `idDepartement` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`commune`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`commune` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`commune` (
  `idCommune` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `Departement_idDepartement` INT(11) NOT NULL,
  PRIMARY KEY (`idCommune`),
  INDEX `fk_Commune_Departement1_idx` (`Departement_idDepartement` ASC),
  CONSTRAINT `fk_Commune_Departement1`
    FOREIGN KEY (`Departement_idDepartement`)
    REFERENCES `projetb2csharp`.`departement` (`idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`equipe` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`equipe` (
  `idEquipe` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `nombreMembres` INT(11) NOT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`espece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`espece` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`espece` (
  `idEspece` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEspece`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`plage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`plage` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`plage` (
  `idPlage` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idCommune` INT(11) NOT NULL,
  `ndEspecesDifferentes` INT(11) NOT NULL,
  `surface` FLOAT NOT NULL,
  PRIMARY KEY (`idPlage`),
  INDEX `fk_Plage_Commune1_idx` (`idCommune` ASC),
  CONSTRAINT `fk_Plage_Commune1`
    FOREIGN KEY (`idCommune`)
    REFERENCES `projetb2csharp`.`commune` (`idCommune`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`espece_has_plage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`espece_has_plage` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`espece_has_plage` (
  `Espece_idEspece` INT(11) NOT NULL,
  `Plage_idPlage` INT(11) NOT NULL,
  `densite` FLOAT NOT NULL,
  `populationTotale` FLOAT NOT NULL,
  PRIMARY KEY (`Espece_idEspece`, `Plage_idPlage`),
  INDEX `fk_Espece_has_Plage_Plage1_idx` (`Plage_idPlage` ASC),
  INDEX `fk_Espece_has_Plage_Espece1_idx` (`Espece_idEspece` ASC),
  CONSTRAINT `fk_Espece_has_Plage_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Espece_has_Plage_Plage1`
    FOREIGN KEY (`Plage_idPlage`)
    REFERENCES `projetb2csharp`.`plage` (`idPlage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`zoneprelevement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`zoneprelevement` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`zoneprelevement` (
  `idZonePrelevement` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `lat1` FLOAT NOT NULL,
  `lat2` FLOAT NOT NULL,
  `lat3` FLOAT NOT NULL,
  `lat4` FLOAT NOT NULL,
  `long1` FLOAT NOT NULL,
  `long2` FLOAT NOT NULL,
  `long3` FLOAT NOT NULL,
  `long4` FLOAT NOT NULL,
  PRIMARY KEY (`idZonePrelevement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`espece_has_zoneprelevement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`espece_has_zoneprelevement` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`espece_has_zoneprelevement` (
  `Espece_idEspece` INT(11) NOT NULL,
  `ZonePrelevement_idZonePrelevement` INT(11) NOT NULL,
  `nombreEspeceZone` INT(11) NOT NULL,
  PRIMARY KEY (`Espece_idEspece`, `ZonePrelevement_idZonePrelevement`),
  INDEX `fk_Espece_has_ZonePrelevement_ZonePrelevement1_idx` (`ZonePrelevement_idZonePrelevement` ASC),
  INDEX `fk_Espece_has_ZonePrelevement_Espece1_idx` (`Espece_idEspece` ASC),
  CONSTRAINT `fk_Espece_has_ZonePrelevement_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Espece_has_ZonePrelevement_ZonePrelevement1`
    FOREIGN KEY (`ZonePrelevement_idZonePrelevement`)
    REFERENCES `projetb2csharp`.`zoneprelevement` (`idZonePrelevement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`etude`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`etude` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`etude` (
  `idEtude` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `nbTotalEspeceRencontree` INT(11) NOT NULL,
  `idEquipe` INT(11) NOT NULL,
  PRIMARY KEY (`idEtude`),
  INDEX `fk_Etude_Equipe1_idx` (`idEquipe` ASC),
  CONSTRAINT `fk_Etude_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `projetb2csharp`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`etude_has_espece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`etude_has_espece` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`etude_has_espece` (
  `Etude_idEtude` INT(11) NOT NULL,
  `Espece_idEspece` INT(11) NOT NULL,
  `densiteTotaleEspece` FLOAT NOT NULL,
  PRIMARY KEY (`Etude_idEtude`, `Espece_idEspece`),
  INDEX `fk_Etude_has_Espece_Espece1_idx` (`Espece_idEspece` ASC),
  INDEX `fk_Etude_has_Espece_Etude1_idx` (`Etude_idEtude` ASC),
  CONSTRAINT `fk_Etude_has_Espece_Espece1`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `projetb2csharp`.`espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etude_has_Espece_Etude1`
    FOREIGN KEY (`Etude_idEtude`)
    REFERENCES `projetb2csharp`.`etude` (`idEtude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`etude_has_plage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`etude_has_plage` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`etude_has_plage` (
  `Etude_idEtude` INT(11) NOT NULL,
  `Plage_idPlage` INT(11) NOT NULL,
  `zoneprelevement_idZonePrelevement` INT(11) NOT NULL,
  `name_concatenation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Etude_idEtude`, `Plage_idPlage`, `zoneprelevement_idZonePrelevement`),
  INDEX `fk_Etude_has_Plage_Plage1_idx` (`Plage_idPlage` ASC),
  INDEX `fk_Etude_has_Plage_Etude1_idx` (`Etude_idEtude` ASC),
  INDEX `fk_etude_has_plage_zoneprelevement1_idx` (`zoneprelevement_idZonePrelevement` ASC),
  CONSTRAINT `fk_Etude_has_Plage_Etude1`
    FOREIGN KEY (`Etude_idEtude`)
    REFERENCES `projetb2csharp`.`etude` (`idEtude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etude_has_Plage_Plage1`
    FOREIGN KEY (`Plage_idPlage`)
    REFERENCES `projetb2csharp`.`plage` (`idPlage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etude_has_plage_zoneprelevement1`
    FOREIGN KEY (`zoneprelevement_idZonePrelevement`)
    REFERENCES `projetb2csharp`.`zoneprelevement` (`idZonePrelevement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`utilisateur` (
  `idUtilisateur` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `isAdmin` BIT(1) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetb2csharp`.`utilisateur_has_equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetb2csharp`.`utilisateur_has_equipe` ;

CREATE TABLE IF NOT EXISTS `projetb2csharp`.`utilisateur_has_equipe` (
  `Utilisateur_idUtilisateur` INT(11) NOT NULL,
  `Equipe_idEquipe` INT(11) NOT NULL,
  PRIMARY KEY (`Utilisateur_idUtilisateur`, `Equipe_idEquipe`),
  INDEX `fk_Utilisateur_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC),
  INDEX `fk_Utilisateur_has_Equipe_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Utilisateur_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `projetb2csharp`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Equipe_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `projetb2csharp`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
